# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saffron/saffron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saffron/saffron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saffron/saffron/CMakeFiles /home/saffron/saffron//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saffron/saffron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named au

# Build rule for target.
au: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 au
.PHONY : au

# fast build rule for target.
au/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/au.dir/build.make CMakeFiles/au.dir/build
.PHONY : au/fast

#=============================================================================
# Target rules for targets named sf

# Build rule for target.
sf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sf
.PHONY : sf

# fast build rule for target.
sf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf.dir/build.make CMakeFiles/sf.dir/build
.PHONY : sf/fast

#=============================================================================
# Target rules for targets named sp

# Build rule for target.
sp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sp
.PHONY : sp

# fast build rule for target.
sp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sp.dir/build.make CMakeFiles/sp.dir/build
.PHONY : sp/fast

#=============================================================================
# Target rules for targets named tw

# Build rule for target.
tw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tw
.PHONY : tw

# fast build rule for target.
tw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/build
.PHONY : tw/fast

#=============================================================================
# Target rules for targets named sf_png2bmp

# Build rule for target.
sf_png2bmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sf_png2bmp
.PHONY : sf_png2bmp

# fast build rule for target.
sf_png2bmp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf_png2bmp.dir/build.make CMakeFiles/sf_png2bmp.dir/build
.PHONY : sf_png2bmp/fast

#=============================================================================
# Target rules for targets named generate_assets

# Build rule for target.
generate_assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_assets
.PHONY : generate_assets

# fast build rule for target.
generate_assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_assets.dir/build.make CMakeFiles/generate_assets.dir/build
.PHONY : generate_assets/fast

sf_examples/au.o: sf_examples/au.c.o
.PHONY : sf_examples/au.o

# target to build an object file
sf_examples/au.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/au.dir/build.make CMakeFiles/au.dir/sf_examples/au.c.o
.PHONY : sf_examples/au.c.o

sf_examples/au.i: sf_examples/au.c.i
.PHONY : sf_examples/au.i

# target to preprocess a source file
sf_examples/au.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/au.dir/build.make CMakeFiles/au.dir/sf_examples/au.c.i
.PHONY : sf_examples/au.c.i

sf_examples/au.s: sf_examples/au.c.s
.PHONY : sf_examples/au.s

# target to generate assembly for a file
sf_examples/au.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/au.dir/build.make CMakeFiles/au.dir/sf_examples/au.c.s
.PHONY : sf_examples/au.c.s

sf_examples/sf.o: sf_examples/sf.c.o
.PHONY : sf_examples/sf.o

# target to build an object file
sf_examples/sf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf.dir/build.make CMakeFiles/sf.dir/sf_examples/sf.c.o
.PHONY : sf_examples/sf.c.o

sf_examples/sf.i: sf_examples/sf.c.i
.PHONY : sf_examples/sf.i

# target to preprocess a source file
sf_examples/sf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf.dir/build.make CMakeFiles/sf.dir/sf_examples/sf.c.i
.PHONY : sf_examples/sf.c.i

sf_examples/sf.s: sf_examples/sf.c.s
.PHONY : sf_examples/sf.s

# target to generate assembly for a file
sf_examples/sf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf.dir/build.make CMakeFiles/sf.dir/sf_examples/sf.c.s
.PHONY : sf_examples/sf.c.s

sf_examples/sp.o: sf_examples/sp.c.o
.PHONY : sf_examples/sp.o

# target to build an object file
sf_examples/sp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sp.dir/build.make CMakeFiles/sp.dir/sf_examples/sp.c.o
.PHONY : sf_examples/sp.c.o

sf_examples/sp.i: sf_examples/sp.c.i
.PHONY : sf_examples/sp.i

# target to preprocess a source file
sf_examples/sp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sp.dir/build.make CMakeFiles/sp.dir/sf_examples/sp.c.i
.PHONY : sf_examples/sp.c.i

sf_examples/sp.s: sf_examples/sp.c.s
.PHONY : sf_examples/sp.s

# target to generate assembly for a file
sf_examples/sp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sp.dir/build.make CMakeFiles/sp.dir/sf_examples/sp.c.s
.PHONY : sf_examples/sp.c.s

sf_examples/tw.o: sf_examples/tw.c.o
.PHONY : sf_examples/tw.o

# target to build an object file
sf_examples/tw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/sf_examples/tw.c.o
.PHONY : sf_examples/tw.c.o

sf_examples/tw.i: sf_examples/tw.c.i
.PHONY : sf_examples/tw.i

# target to preprocess a source file
sf_examples/tw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/sf_examples/tw.c.i
.PHONY : sf_examples/tw.c.i

sf_examples/tw.s: sf_examples/tw.c.s
.PHONY : sf_examples/tw.s

# target to generate assembly for a file
sf_examples/tw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/sf_examples/tw.c.s
.PHONY : sf_examples/tw.c.s

sf_extras/sf_png2bmp.o: sf_extras/sf_png2bmp.c.o
.PHONY : sf_extras/sf_png2bmp.o

# target to build an object file
sf_extras/sf_png2bmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf_png2bmp.dir/build.make CMakeFiles/sf_png2bmp.dir/sf_extras/sf_png2bmp.c.o
.PHONY : sf_extras/sf_png2bmp.c.o

sf_extras/sf_png2bmp.i: sf_extras/sf_png2bmp.c.i
.PHONY : sf_extras/sf_png2bmp.i

# target to preprocess a source file
sf_extras/sf_png2bmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf_png2bmp.dir/build.make CMakeFiles/sf_png2bmp.dir/sf_extras/sf_png2bmp.c.i
.PHONY : sf_extras/sf_png2bmp.c.i

sf_extras/sf_png2bmp.s: sf_extras/sf_png2bmp.c.s
.PHONY : sf_extras/sf_png2bmp.s

# target to generate assembly for a file
sf_extras/sf_png2bmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sf_png2bmp.dir/build.make CMakeFiles/sf_png2bmp.dir/sf_extras/sf_png2bmp.c.s
.PHONY : sf_extras/sf_png2bmp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... generate_assets"
	@echo "... au"
	@echo "... sf"
	@echo "... sf_png2bmp"
	@echo "... sp"
	@echo "... tw"
	@echo "... sf_examples/au.o"
	@echo "... sf_examples/au.i"
	@echo "... sf_examples/au.s"
	@echo "... sf_examples/sf.o"
	@echo "... sf_examples/sf.i"
	@echo "... sf_examples/sf.s"
	@echo "... sf_examples/sp.o"
	@echo "... sf_examples/sp.i"
	@echo "... sf_examples/sp.s"
	@echo "... sf_examples/tw.o"
	@echo "... sf_examples/tw.i"
	@echo "... sf_examples/tw.s"
	@echo "... sf_extras/sf_png2bmp.o"
	@echo "... sf_extras/sf_png2bmp.i"
	@echo "... sf_extras/sf_png2bmp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

